# Generated by Django 5.1 on 2024-09-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255, unique=True)),
                ("lr", models.FloatField()),
                ("epoch", models.IntegerField()),
                ("batch_size", models.IntegerField()),
                ("loss_epoch", models.TextField()),
                ("accuracy_epoch", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration", models.FloatField()),
            ],
        ),
    ]
